name: CI

on: [pull_request, push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: â¬‡ Checkout
        uses: actions/checkout@v4

      - name: ğŸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ’° Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: â¬‡ Checkout
        uses: actions/checkout@v4

      - name: ğŸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: âœ… Run unit tests
        run: |
          pytest -n auto --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov .

      - name: ğŸ† Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ./pytest.xml
          title: Coverage Report
          badge-title: Coverage Badge
          hide-badge: false
          hide-report: false
          hide-comment: false
          report-only-changed-files: true
          remove-link-from-badge: false
          junitxml-title: XML Report Summary
